# Generated by Django 5.2.17 on 2026-09-05 13:52

import django.core.validators
import django.db.models.deletion
import django.db.models.manager
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('station_code', models.CharField(help_text='Official short code, for example NDLS or BCT.', max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='Station code must be 2-10 characters using A-Z and 0-9 only.', regex='^[A-Z0-9]{2,10}$')])),
                ('city', models.CharField(max_length=80)),
                ('state', models.CharField(max_length=80)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Station',
                'verbose_name_plural': 'Stations',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('route_name', models.CharField(max_length=120, unique=True)),
                ('total_distance', models.DecimalField(decimal_places=2, help_text='Total route length in kilometres.', max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('is_active', models.BooleanField(default=True)),
                ('destination_station', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='routes_to', to='railway.station')),
                ('source_station', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='routes_from', to='railway.station')),
            ],
            options={
                'verbose_name': 'Route',
                'verbose_name_plural': 'Routes',
                'ordering': ['route_name'],
            },
        ),
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('platform_number', models.PositiveIntegerField(help_text='Platform number between 1 and 99.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(99)])),
                ('is_active', models.BooleanField(default=True)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='platforms', to='railway.station')),
            ],
            options={
                'verbose_name': 'Platform',
                'verbose_name_plural': 'Platforms',
                'ordering': ['station__name', 'platform_number'],
            },
        ),
        migrations.CreateModel(
            name='Train',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('train_number', models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='Train number must be 4 to 6 digits, for example 12951.', regex='^[0-9]{4,6}$')])),
                ('train_name', models.CharField(max_length=120)),
                ('total_coaches', models.PositiveIntegerField(default=18, help_text='Number of coaches in the rake (1-30).', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(30)])),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('MAINTENANCE', 'Maintenance'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=12)),
                ('is_deleted', models.BooleanField(default=False)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trains', to='railway.route')),
            ],
            options={
                'verbose_name': 'Train',
                'verbose_name_plural': 'Trains',
                'ordering': ['train_number'],
                'base_manager_name': 'all_objects',
                'default_manager_name': 'objects',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('departure_datetime', models.DateTimeField()),
                ('arrival_datetime', models.DateTimeField()),
                ('delay_minutes', models.PositiveIntegerField(default=0, help_text='Current running delay in minutes (0 when on time).', validators=[django.core.validators.MaxValueValidator(1440)])),
                ('is_cancelled', models.BooleanField(default=False)),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='schedules', to='railway.platform')),
                ('train', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='railway.train')),
            ],
            options={
                'verbose_name': 'Schedule',
                'verbose_name_plural': 'Schedules',
                'ordering': ['-departure_datetime'],
            },
        ),
        migrations.CreateModel(
            name='RouteStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sequence_number', models.PositiveIntegerField(help_text='Position of this halt on the route, starting at 1.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(200)])),
                ('arrival_offset', models.PositiveIntegerField(default=0, help_text='Minutes after the origin departure when the train arrives here.', validators=[django.core.validators.MaxValueValidator(10080)])),
                ('departure_offset', models.PositiveIntegerField(default=0, help_text='Minutes after the origin departure when the train leaves here.', validators=[django.core.validators.MaxValueValidator(10080)])),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_stations', to='railway.route')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='route_stations', to='railway.station')),
            ],
            options={
                'verbose_name': 'Route Station',
                'verbose_name_plural': 'Route Stations',
                'ordering': ['route__route_name', 'sequence_number'],
                'constraints': [models.UniqueConstraint(fields=('route', 'sequence_number'), name='unique_sequence_number_per_route', violation_error_message='This sequence number is already used on the selected route.'), models.UniqueConstraint(fields=('route', 'station'), name='unique_station_per_route', violation_error_message='This station is already part of the selected route.')],
            },
        ),
        migrations.AddConstraint(
            model_name='platform',
            constraint=models.UniqueConstraint(fields=('station', 'platform_number'), name='unique_platform_number_per_station', violation_error_message='This platform number already exists for the selected station.'),
        ),
        migrations.AddIndex(
            model_name='schedule',
            index=models.Index(fields=['departure_datetime'], name='schedule_departure_idx'),
        ),
    ]
